### ISSUE TITLE
Priorities for 0.1.0

### ISSUE THREAD

**Issue by PgBiel** [PgBiel/typst-tablex#127]
With my recent progress in porting many of tablex's main features to Typst built-in tables (https://github.com/typst/typst/issues/3001), it is to lay out some preliminary plans for Tablex 0.1.0.

- The new renderer proposed in #2 would be indefinitely postponed, given that it would basically mimic built-in tables' layout algorithms without much gain (given the effort that would be required to implement that).
- Instead, we'd focus on two new rendering backends.
   - [ ] **CeTZ backend** (#77): stands out by allowing easy annotations over cells.
   - [ ] **Native backend:** Would be a best effort to allow using tablex syntax to generate native tables.
   - The current backend ("old") would be kept for compatibility.
- [ ] We should experiment with implementing a `value` field for tablex cells in order to allow one to access the values directly specified to the table before they are transformed into content, allowing for some basic spreadsheet-like functionality (going further than that is out of scope).
